default: &default
    adapter: mysql2
    username: root
    password: 'root'
    host: 127.0.0.1
    reconnect: true
    pool: 15
    
development:
    <<: *default
    database: payment_dev

test:
    <<: *default
    database: payment_test

production:
    <<: *default
    database: payment_prod